# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-TT-Filters-LazyLoader
version:      0.03
version_from: lib/Catalyst/View/TT/Filters/LazyLoader.pm
installdirs:  site
requires:
    Catalyst:                      5.7
    Catalyst::View::TT:            0
    Template::Filters::LazyLoader: 0.04
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
